"""initial

Revision ID: e267a7d0e207
Revises: 
Create Date: 2025-11-18 12:30:06.679832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e267a7d0e207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppTikTokSession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiktok_name', sa.String(length=256), nullable=True),
    sa.Column('ms_token', sa.String(length=512), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.Column('storage_state', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('headless', sa.Boolean(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppTikTokSession')
    # ### end Alembic commands ###
