"""add_account

Revision ID: eeaf3dcf46b9
Revises: e267a7d0e207
Create Date: 2025-11-18 16:38:21.753043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaf3dcf46b9'
down_revision = 'e267a7d0e207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AppTikTokSession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['account'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AppTikTokSession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('account')

    # ### end Alembic commands ###
